/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aloxide.sdk.java.gradle;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting() + " ---- " + Arrays.toString(args));
    }
}
